# Generated by Django 5.0.4 on 2026-03-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_configuracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_inscripcion',
            field=models.DateField(),
        ),
    ]
